---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
non-functional:
  - Сайт должен быть доступен на различных устройствах
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен иметь мобильную версию
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
implicit:
  - Пользователь должен иметь возможность пройти регистрацию и оставить свои данные для заказа